# Análise do Exame Realizado em 2024

In [1]:
!pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------- ----- 8.4/9.8 MB 63.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 26.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 24.7 MB/s  0:00:00
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------  12.6/12.7 MB 62.7 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 50.2 MB/s  0:00:00
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.3 pandas-3.0.6

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------  9.4/9.5 MB 56.1 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 46.0 MB/s  0:00:00
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 40.1 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 48.9 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 pyparsing-3.3.2

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

## Carregando os Dados dos Participantes

In [4]:
df_participantes = pd.read_csv(
                    "data/2024/PARTICIPANTES_2024.csv",
                    sep=";",
                    encoding="latin1"
)

## Exibindo Informações sobre o Dataset
Exibindo o total de linhas e colunas

In [5]:
df_participantes.shape

(4332944, 38)

Exibindo as primeiras linhas do arquivo

In [6]:
df_participantes.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,0,4314902,Porto Alegre,43,RS,F,F,C,D,4,B,C,A,C,D,C,B,B,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,0,4318903,São Luiz Gonzaga,43,RS,B,C,A,D,2,B,E,A,B,B,B,B,B,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,0,4320107,Sarandi,43,RS,H,F,F,D,5,B,J,A,C,D,B,B,C,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,0,4313409,Novo Hamburgo,43,RS,B,B,B,B,6,A,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,0,4309209,Gravataí,43,RS,B,B,C,C,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A

Lista de colunas

In [7]:
df_participantes.columns.tolist()

['NU_INSCRICAO',
 'NU_ANO',
 'TP_FAIXA_ETARIA',
 'TP_SEXO',
 'TP_ESTADO_CIVIL',
 'TP_COR_RACA',
 'TP_NACIONALIDADE',
 'TP_ST_CONCLUSAO',
 'TP_ANO_CONCLUIU',
 'TP_ENSINO',
 'IN_TREINEIRO',
 'CO_MUNICIPIO_PROVA',
 'NO_MUNICIPIO_PROVA',
 'CO_UF_PROVA',
 'SG_UF_PROVA',
 'Q001',
 'Q002',
 'Q003',
 'Q004',
 'Q005',
 'Q006',
 'Q007',
 'Q008',
 'Q009',
 'Q010',
 'Q011',
 'Q012',
 'Q013',
 'Q014',
 'Q015',
 'Q016',
 'Q017',
 'Q018',
 'Q019',
 'Q020',
 'Q021',
 'Q022',
 'Q023']

### Descrição do Significado das Colunas do Dataset de Participantes

'NU_INSCRICAO' - (Numérico) - Máscara do Número de Inscrição do Candidato  

 'NU_ANO' - Ano de realização do exame  
 
 'TP_FAIXA_ETARIA' - Dividida em 20 categorias, representando desde de candidatos com idade inferior a 16 anos àqueles com idade superior a 70 anos.  
 
 **'TP_SEXO' - Sexo Biológico M - Masculino / F - Feminino**  
 
 'TP_ESTADO_CIVIL' - Estado Civil  
 
 **'TP_COR_RACA' - Cor/raça (Valores: 1 - 6)**  
 
 'TP_NACIONALIDADE' - Nacionalidade  
 
 'TP_ST_CONCLUSAO' - Situação de conclusão do Ensino Médio (Valores: 1 - 4)  
 
 'TP_ANO_CONCLUIU' - Ano de conclusão do Ensino Médio (Valores: 0 - 18)  
 
 'TP_ENSINO' - Tipo de instituição que concluiu ou concluirá o Ensino Médio (Valores: 1 - 2)  
 
 'IN_TREINEIRO' - Indica se o inscrito fez a prova com intuito de apenas treinar seus conhecimentos (Valores: 0 - 1)  
 
 'CO_MUNICIPIO_PROVA' - Código do município da aplicação da prova  
 
 'NO_MUNICIPIO_PROVA' - Nome do município da aplicação da prova  
 
 'CO_UF_PROVA' - Código da UF da aplicação da prova  
 
 'SG_UF_PROVA' - Sigla da UF da aplicação da prova  
 
 'Q001' - Até que série seu pai, ou o homem responsável por você, estudou? (Valores: A - H)  
 
 'Q002' - Até que série sua mãe, ou a mulher responsável por você, estudou? (Valores: A - H)  
 
 'Q003' - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação do seu pai ou do homem responsável por você. (Se ele não estiver trabalhando, escolha uma ocupação pensando no último trabalho dele). (Valores: A - F)  
 
 'Q004' - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação da sua mãe ou da mulher responsável por você. (Se ela não estiver trabalhando, escolha uma ocupação pensando no último trabalho dela). (Valores: A - F)  
 
 **'Q005' - Incluindo você, quantas pessoas moram atualmente em sua residência?  (Valores: 1 - 20)**  
 
 'Q006' - Você possui renda? (Valores: A - B)  
 
 **'Q007' - Qual é a renda mensal de sua família? (Considere a sua renda com a das pessoas que moram com você.) (Valores: A - Q)**  
 
 'Q008' - Em sua casa, você ou a pessoa responsável pela sua família costuma contratar os serviços de um(a) empregado(a) doméstico(a)?  
 
 'Q009' - Em sua casa, existe banheiro?  
 
 'Q010' - Em sua casa, existe quarto para dormir?  
 
 'Q011' - Incluindo você, as pessoas com quem você mora têm carro?  
 
 'Q012' - Incluindo você, as pessoas com quem você mora têm motocicleta?  
 
 'Q013' - Em sua casa, existe geladeira?  
 
 'Q014' - Em sua casa, existe freezer independente (vertical ou horizontal)? (Não considere a segunda porta da geladeira.)  
 
 'Q015' - Em sua casa, existe máquina de lavar roupa? (Não considere o tanquinho.)  
 
 'Q016' - Em sua casa, existe micro-ondas?   
 
 'Q017' - Em sua casa, existe aspirador de pó?  
 
 'Q018' - Em sua casa, existe aparelho de TV?  
 
 'Q019' - Em sua casa, existe TV por assinatura?  
 
 'Q020' - Em sua casa, existe acesso à internet por rede wi-fi?  
 
 'Q021' - Em sua casa, existe computador/notebook?  
 
 'Q022' - Incluindo você, as pessoas com quem você mora têm telefone celular?  
 
 'Q023' - Em que tipo de escola você frequentou ou frequenta o Ensino Médio?

In [8]:
df_participantes.loc[df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro']

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306106,210066468737,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,E,A,A,3,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
4315570,210066478202,2024,2,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,B,F,B,5,A,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,B,A
4319320,210066481955,2024,3,F,1,1,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,B,B,4,A,B,B,B,D,B,A,B,A,B,B,A,B,A,B,B,D,A
4322809,210066485444,2024,7,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,D,E,C,B,4,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,B,C,E
4330767,210066493402,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,G,B,D,3,A,H,A,D,D,B,B,B,B,B,B,B,D,A,B,D,D,D

In [21]:
df_participantes[df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro']['SG_UF_PROVA'].unique()

<StringArray>
['BA']
Length: 1, dtype: str

## Recuperando os Participantes de Santo Amaro - BA

In [24]:
df_participantes_santo_amaro = df_participantes[
    (df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro') & (df_participantes['SG_UF_PROVA'] == 'BA') ]

In [25]:
df_participantes_santo_amaro.head(50)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
27943,210062093585,2024,13,F,1,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,B,A,A,B,1,B,A,A,B,B,A,A,B,A,A,A,A,A,A,B,B,B,A
32317,210062097960,2024,4,M,1,3,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,G,E,D,C,4,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
38485,210062104129,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,G,B,D,4,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,D
38782,210062104426,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,G,B,D,2,A,F,A,B,C,A,A,B,A,B,B,B,C,A,B,C,B,D
40250,210062105894,2024,1,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,G,A,B,D,B,A,C,A,B,B,B,B,B,B,B,D,A
40860,210062106504,2024,4,F,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,H,E,F,A,6,A,B,A,B,D,A,A,B,A,A,A,A,B,A,B,A,D,A
43674,210062109321,2024,13,F,1,2,1,1,16,NaN,0,2928604,Santo Amaro,29,BA,B,B,C,F,2,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
47425,210062113073,2024,2,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,F,A,C,D,A,A,B,B,B,B,B,B,A,B,B,E,A
56297,210062122449,2024,5,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,G,H,D,E,4,A,C,A,C,D,A,A,B,A,B,B,B,D,A,B,A,E,A
58625,210062124778,2024,6,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,A,B,C,B,2,A,A,A,B,C,A,A,B,A,B,B,A,B,A,B,A,C,A
59443,210062125596,2024,4,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,E,A,A,5,A,B,A,B,D,A,A,B,A,A,B,A,B,A,B,A,C,A
60244,210062126398,2024,1,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,F,E,D,D,2,A,L,A,B,C,B,A,B,A,B,A,A,C,B,B,C,D,D
65842,210062131998,2024,2,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,F,C,B,3,A,F,A,C,C,A,A,B,A,B,B,B,B,B,B,B,E,A
70055,210062136284,2024,2,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,H,D,D,D,6,A,B,A,B,D,A,A,B,A,A,B,A,C,A,B,A,E,A
71462,210062137744,2024,7,M,1,2,1,2,0,NaN,0,2928604,Santo Amaro,29,BA,E,E,F,F,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
74760,210062141327,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,C,E,D,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,A,A,C,A
78233,210062145014,2024,7,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,C,E,B,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
79851,210062146632,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,H,H,B,F,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
80527,210062147310,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,F,B,3,A,B,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
80530,210062147313,2024,2,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,D,E,F,F,4,A,A,A,B,B,A,A,B,A,B,A,A,B,A,B,A,B,A
84697,210062151494,2024,10,M,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,C,E,B,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
84916,210062151713,2024,9,F,1,2,1,1,6,NaN,0,2928604,Santo Amaro,29,BA,E,D,B,B,3,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
87557,210062154355,2024,8,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,B,4,A,C,A,C,D,A,A,B,A,A,A,A,C,A,B,A,E,A
88704,210062155503,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,H,E,F,F,5,A,B,A,B,B,A,A,A,A,A,A,A,A,A,B,A,B,A
94144,210062160945,2024,2,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,C,E,B,B,5,A,B,A,B,C,A,B,B,A,A,A,A,B,A,A,A,D,A
95797,210062162599,2024,5,F,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,B,A,A,5,A,B,A,B,C,A,A,B,A,A,A,A,C,A,B,A,E,A
96526,210062163328,2024,6,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,B,E,A,B,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
97243,210062164045,2024,3,F,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,D,E,A,A,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,A,A,C,A
100766,210062167845,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,A,B,A,A,9,A,A,A,A,D,A,A,B,A,A,A,A,B,A,B,A,C,A
102159,210062170724,2024,4,M,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,E,C,A,A,5,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
106846,210062175725,2024,1,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,E,B,B,5,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
108656,210062177535,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,D,F,B,3,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
109807,210062178687,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,B,F,B,4,A,B,A,B,B,A,A,B,A,A,A,A,B,A,A,A,C,A
110188,210062179068,2024,6,M,1,3,1,1,4,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,B,6,A,B,A,B,C,A,A,B,B,A,A,A,B,A,A,A,C,A
114083,210062182964,2024,3,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,B,C,B,3,A,B,A,B,D,A,A,B,B,B,A,A,B,A,B,A,B,A
114095,210062182976,2024,4,F,1,2,1,1,0,NaN,0,2928604,Santo Amaro,29,BA,A,B,A,B,2,A,A,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
122366,210062191283,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,D,B,B,3,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,D,A
122874,210062191828,2024,5,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,C,D,4,A,E,A,B,C,B,B,B,A,A,B,A,B,A,B,B,E,A
127815,210062196946,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,B,B,B,3,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,A,C,A
129992,210062199123,2024,6,M,1,2,1,2,0,NaN,0,2928604,Santo Amaro,29,BA,B,B,B,B,1,B,B,A,B,C,A,A,A,A,A,A,A,A,A,A,A,B,A
130716,210062199848,2024,5,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,A,A,A,A,3,A,B,A,B,D,A,A,B,A,A,A,A,B,A,A,A,C,A
136158,210062205291,2024,1,F,1,2,1,4,0,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,D,4,A,B,A,C,D,A,A,B,A,A,A,A,C,A,B,C,E,F
141870,210062211006,2024,14,F,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,B,E,A,A,2,B,C,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
144263,210062213401,2024,11,M,1,3,1,1,8,NaN,0,2928604,Santo Amaro,29,BA,E,B,C,B,9,B,E,A,B,D,B,B,C,A,B,A,A,D,A,B,A,E,A
145524,210062214662,2024,1,M,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,C,B,2,A,B,A,B,C,A,A,B,A,B,A,A,B,A,B,B,B,A

## Definindo Participantes de Baixa renda

https://brasilescola.uol.com.br/geografia/renda-per-capita.htm#Renda+per+capita+familiar  

https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/45942-ibge-divulga-rendimento-domiciliar-per-capita-2025-para-brasil-e-unidades-da-federacao  

https://mundoeducacao.uol.com.br/geografia/renda-per-capita.htm  

**https://www.serasa.com.br/blog/baixa-renda/ ()**  

### O que é baixa renda
Baixa renda é um termo utilizado para definir famílias ou indivíduos com renda mensal insuficiente para atender plenamente a necessidades básicas, como alimentação, moradia, saúde, educação e transporte.

Essa classificação varia de acordo com a região e o custo de vida local, mas em geral está associada àqueles que vivem com rendimento abaixo da média nacional.

Pessoas de baixa renda enfrentam diversos desafios que perpetuam o ciclo de pobreza:
 
● falta de acesso a oportunidades de educação e emprego de qualidade;
● preconceito, discriminação e barreiras sociais que dificultam a integração e ascensão social.
● maior exposição a ambientes violentos e a atividades criminosas;
● instabilidade financeira e falta de uma rede de segurança em casos de emergência;
● saúde precária e acesso limitado a cuidados médicos e saneamento básico.
 

**Para saber quem se enquadra nesse critério, basta fazer um cálculo simples: somar a renda da casa e dividi-la pelo número de pessoas que vivem ali. Se o resultado for igual ou inferior a R$706, que representa meio salário mínimo, então aquela família pode ser considerada de baixa renda.**