# Análise do Exame Realizado em 2024
Este projeto tem por finalidade explorar e analisar os microdados do ENEM realizado no ano de 2024. Durante a condução deste projeto, se dará maior ênfase aos achados relacionados ao município de Santo Amaro da Purificação - BA. Dentre as análises que serão realizadas, procura-se responder:  
- Qual foi o desempenho dos estudantes que realizaram o exame na cidade de Santo Amaro?
- Como esse desempenho se compara ao resultado nacional?
- Quantos estudantes de baixa renda realizaram o exame em 2024?
- Qual a relação entre o número de candidatos do sexo masculino e o número de candidatos do sexo feminido (considerando apenas o sexo biológico, já que este é o único dado de gênero presente no dataset)?
- Qual é a quantidade candidatos negros e pardos que realizaram o exame em 2024?
- Qual é a relação existente entre a renda familiar e os resultados obtidos pelos candidatos?

In [1]:
!pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------- ----- 8.4/9.8 MB 63.4 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 26.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 24.7 MB/s  0:00:00
Downloading numpy-2.5.3-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------  12.6/12.7 MB 62.7 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 50.2 MB/s  0:00:00
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.3 pandas-3.0.6

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------  9.4/9.5 MB 56.1 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 46.0 MB/s  0:00:00
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp314-cp314-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------------------------------- 2.5/2.5 MB 40.1 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 48.9 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 pyparsing-3.3.2

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\alexsandro.santos\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

## Carregando os Dados dos Participantes

In [3]:
df_participantes = pd.read_csv(
                    "data/2024/PARTICIPANTES_2024.csv",
                    sep=";",
                    encoding="latin1"
)

## Exibindo Informações sobre o Dataset
Exibindo o total de linhas e colunas

In [4]:
df_participantes.shape

(4332944, 38)

Exibindo as primeiras linhas do arquivo

In [5]:
df_participantes.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,0,4314902,Porto Alegre,43,RS,F,F,C,D,4,B,C,A,C,D,C,B,B,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,0,4318903,São Luiz Gonzaga,43,RS,B,C,A,D,2,B,E,A,B,B,B,B,B,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,0,4320107,Sarandi,43,RS,H,F,F,D,5,B,J,A,C,D,B,B,C,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,0,4313409,Novo Hamburgo,43,RS,B,B,B,B,6,A,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,0,4309209,Gravataí,43,RS,B,B,C,C,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A

Lista de colunas

In [6]:
df_participantes.columns.tolist()

['NU_INSCRICAO',
 'NU_ANO',
 'TP_FAIXA_ETARIA',
 'TP_SEXO',
 'TP_ESTADO_CIVIL',
 'TP_COR_RACA',
 'TP_NACIONALIDADE',
 'TP_ST_CONCLUSAO',
 'TP_ANO_CONCLUIU',
 'TP_ENSINO',
 'IN_TREINEIRO',
 'CO_MUNICIPIO_PROVA',
 'NO_MUNICIPIO_PROVA',
 'CO_UF_PROVA',
 'SG_UF_PROVA',
 'Q001',
 'Q002',
 'Q003',
 'Q004',
 'Q005',
 'Q006',
 'Q007',
 'Q008',
 'Q009',
 'Q010',
 'Q011',
 'Q012',
 'Q013',
 'Q014',
 'Q015',
 'Q016',
 'Q017',
 'Q018',
 'Q019',
 'Q020',
 'Q021',
 'Q022',
 'Q023']

### Descrição do Significado das Colunas do Dataset de Participantes

'NU_INSCRICAO' - (Numérico) - Máscara do Número de Inscrição do Candidato  

 'NU_ANO' - Ano de realização do exame  
 
 'TP_FAIXA_ETARIA' - Dividida em 20 categorias, representando desde de candidatos com idade inferior a 16 anos àqueles com idade superior a 70 anos.  
 
 **'TP_SEXO' - Sexo Biológico M - Masculino / F - Feminino**  
 
 'TP_ESTADO_CIVIL' - Estado Civil  
 
 **'TP_COR_RACA' - Cor/raça (Valores: 1 - 6)**  
 
 'TP_NACIONALIDADE' - Nacionalidade  
 
 'TP_ST_CONCLUSAO' - Situação de conclusão do Ensino Médio (Valores: 1 - 4)  
 
 'TP_ANO_CONCLUIU' - Ano de conclusão do Ensino Médio (Valores: 0 - 18)  
 
 'TP_ENSINO' - Tipo de instituição que concluiu ou concluirá o Ensino Médio (Valores: 1 - 2)  
 
 'IN_TREINEIRO' - Indica se o inscrito fez a prova com intuito de apenas treinar seus conhecimentos (Valores: 0 - 1)  
 
 'CO_MUNICIPIO_PROVA' - Código do município da aplicação da prova  
 
 'NO_MUNICIPIO_PROVA' - Nome do município da aplicação da prova  
 
 'CO_UF_PROVA' - Código da UF da aplicação da prova  
 
 'SG_UF_PROVA' - Sigla da UF da aplicação da prova  
 
 'Q001' - Até que série seu pai, ou o homem responsável por você, estudou? (Valores: A - H)  
 
 'Q002' - Até que série sua mãe, ou a mulher responsável por você, estudou? (Valores: A - H)  
 
 'Q003' - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação do seu pai ou do homem responsável por você. (Se ele não estiver trabalhando, escolha uma ocupação pensando no último trabalho dele). (Valores: A - F)  
 
 'Q004' - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação da sua mãe ou da mulher responsável por você. (Se ela não estiver trabalhando, escolha uma ocupação pensando no último trabalho dela). (Valores: A - F)  
 
 **'Q005' - Incluindo você, quantas pessoas moram atualmente em sua residência?  (Valores: 1 - 20)**  
 
 'Q006' - Você possui renda? (Valores: A - B)  
 
 **'Q007' - Qual é a renda mensal de sua família? (Considere a sua renda com a das pessoas que moram com você.) (Valores: A - Q)**  
 
 'Q008' - Em sua casa, você ou a pessoa responsável pela sua família costuma contratar os serviços de um(a) empregado(a) doméstico(a)?  
 
 'Q009' - Em sua casa, existe banheiro?  
 
 'Q010' - Em sua casa, existe quarto para dormir?  
 
 'Q011' - Incluindo você, as pessoas com quem você mora têm carro?  
 
 'Q012' - Incluindo você, as pessoas com quem você mora têm motocicleta?  
 
 'Q013' - Em sua casa, existe geladeira?  
 
 'Q014' - Em sua casa, existe freezer independente (vertical ou horizontal)? (Não considere a segunda porta da geladeira.)  
 
 'Q015' - Em sua casa, existe máquina de lavar roupa? (Não considere o tanquinho.)  
 
 'Q016' - Em sua casa, existe micro-ondas?   
 
 'Q017' - Em sua casa, existe aspirador de pó?  
 
 'Q018' - Em sua casa, existe aparelho de TV?  
 
 'Q019' - Em sua casa, existe TV por assinatura?  
 
 'Q020' - Em sua casa, existe acesso à internet por rede wi-fi?  
 
 'Q021' - Em sua casa, existe computador/notebook?  
 
 'Q022' - Incluindo você, as pessoas com quem você mora têm telefone celular?  
 
 'Q023' - Em que tipo de escola você frequentou ou frequenta o Ensino Médio?

In [7]:
df_participantes.loc[df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro']

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306106,210066468737,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,E,A,A,3,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
4315570,210066478202,2024,2,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,B,F,B,5,A,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,B,A
4319320,210066481955,2024,3,F,1,1,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,B,B,4,A,B,B,B,D,B,A,B,A,B,B,A,B,A,B,B,D,A
4322809,210066485444,2024,7,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,D,E,C,B,4,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,B,C,E
4330767,210066493402,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,G,B,D,3,A,H,A,D,D,B,B,B,B,B,B,B,D,A,B,D,D,D

In [21]:
df_participantes[df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro']['SG_UF_PROVA'].unique()

<StringArray>
['BA']
Length: 1, dtype: str

## Recuperando os Participantes de Santo Amaro - BA

In [10]:
df_santo_amaro = df_participantes[
    (df_participantes['NO_MUNICIPIO_PROVA'] == 'Santo Amaro') & (df_participantes['SG_UF_PROVA'] == 'BA') ]

In [11]:
df_participantes_santo_amaro.head(50)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
27943,210062093585,2024,13,F,1,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,B,A,A,B,1,B,A,A,B,B,A,A,B,A,A,A,A,A,A,B,B,B,A
32317,210062097960,2024,4,M,1,3,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,G,E,D,C,4,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A
38485,210062104129,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,G,B,D,4,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,D
38782,210062104426,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,G,B,D,2,A,F,A,B,C,A,A,B,A,B,B,B,C,A,B,C,B,D
40250,210062105894,2024,1,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,G,A,B,D,B,A,C,A,B,B,B,B,B,B,B,D,A
40860,210062106504,2024,4,F,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,H,E,F,A,6,A,B,A,B,D,A,A,B,A,A,A,A,B,A,B,A,D,A
43674,210062109321,2024,13,F,1,2,1,1,16,NaN,0,2928604,Santo Amaro,29,BA,B,B,C,F,2,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
47425,210062113073,2024,2,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,F,A,C,D,A,A,B,B,B,B,B,B,A,B,B,E,A
56297,210062122449,2024,5,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,G,H,D,E,4,A,C,A,C,D,A,A,B,A,B,B,B,D,A,B,A,E,A
58625,210062124778,2024,6,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,A,B,C,B,2,A,A,A,B,C,A,A,B,A,B,B,A,B,A,B,A,C,A
59443,210062125596,2024,4,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,E,A,A,5,A,B,A,B,D,A,A,B,A,A,B,A,B,A,B,A,C,A
60244,210062126398,2024,1,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,F,E,D,D,2,A,L,A,B,C,B,A,B,A,B,A,A,C,B,B,C,D,D
65842,210062131998,2024,2,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,F,C,B,3,A,F,A,C,C,A,A,B,A,B,B,B,B,B,B,B,E,A
70055,210062136284,2024,2,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,H,D,D,D,6,A,B,A,B,D,A,A,B,A,A,B,A,C,A,B,A,E,A
71462,210062137744,2024,7,M,1,2,1,2,0,NaN,0,2928604,Santo Amaro,29,BA,E,E,F,F,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
74760,210062141327,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,C,E,D,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,A,A,C,A
78233,210062145014,2024,7,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,C,E,B,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
79851,210062146632,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,H,H,B,F,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
80527,210062147310,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,F,B,3,A,B,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
80530,210062147313,2024,2,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,D,E,F,F,4,A,A,A,B,B,A,A,B,A,B,A,A,B,A,B,A,B,A
84697,210062151494,2024,10,M,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,C,E,B,B,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
84916,210062151713,2024,9,F,1,2,1,1,6,NaN,0,2928604,Santo Amaro,29,BA,E,D,B,B,3,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
87557,210062154355,2024,8,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,B,4,A,C,A,C,D,A,A,B,A,A,A,A,C,A,B,A,E,A
88704,210062155503,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,H,E,F,F,5,A,B,A,B,B,A,A,A,A,A,A,A,A,A,B,A,B,A
94144,210062160945,2024,2,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,C,E,B,B,5,A,B,A,B,C,A,B,B,A,A,A,A,B,A,A,A,D,A
95797,210062162599,2024,5,F,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,B,A,A,5,A,B,A,B,C,A,A,B,A,A,A,A,C,A,B,A,E,A
96526,210062163328,2024,6,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,B,E,A,B,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
97243,210062164045,2024,3,F,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,D,E,A,A,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,A,A,C,A
100766,210062167845,2024,3,F,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,A,B,A,A,9,A,A,A,A,D,A,A,B,A,A,A,A,B,A,B,A,C,A
102159,210062170724,2024,4,M,1,2,1,1,1,NaN,0,2928604,Santo Amaro,29,BA,E,C,A,A,5,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
106846,210062175725,2024,1,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,E,B,B,5,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
108656,210062177535,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,D,F,B,3,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A
109807,210062178687,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,B,F,B,4,A,B,A,B,B,A,A,B,A,A,A,A,B,A,A,A,C,A
110188,210062179068,2024,6,M,1,3,1,1,4,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,B,6,A,B,A,B,C,A,A,B,B,A,A,A,B,A,A,A,C,A
114083,210062182964,2024,3,M,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,B,C,B,3,A,B,A,B,D,A,A,B,B,B,A,A,B,A,B,A,B,A
114095,210062182976,2024,4,F,1,2,1,1,0,NaN,0,2928604,Santo Amaro,29,BA,A,B,A,B,2,A,A,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
122366,210062191283,2024,3,F,1,2,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,B,D,B,B,3,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,D,A
122874,210062191828,2024,5,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,C,D,4,A,E,A,B,C,B,B,B,A,A,B,A,B,A,B,B,E,A
127815,210062196946,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,B,B,B,3,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,A,C,A
129992,210062199123,2024,6,M,1,2,1,2,0,NaN,0,2928604,Santo Amaro,29,BA,B,B,B,B,1,B,B,A,B,C,A,A,A,A,A,A,A,A,A,A,A,B,A
130716,210062199848,2024,5,F,1,2,1,1,3,NaN,0,2928604,Santo Amaro,29,BA,A,A,A,A,3,A,B,A,B,D,A,A,B,A,A,A,A,B,A,A,A,C,A
136158,210062205291,2024,1,F,1,2,1,4,0,NaN,0,2928604,Santo Amaro,29,BA,E,E,C,D,4,A,B,A,C,D,A,A,B,A,A,A,A,C,A,B,C,E,F
141870,210062211006,2024,14,F,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,B,E,A,A,2,B,C,A,B,B,A,A,B,A,A,A,A,B,A,B,A,C,A
144263,210062213401,2024,11,M,1,3,1,1,8,NaN,0,2928604,Santo Amaro,29,BA,E,B,C,B,9,B,E,A,B,D,B,B,C,A,B,A,A,D,A,B,A,E,A
145524,210062214662,2024,1,M,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,E,E,C,B,2,A,B,A,B,C,A,A,B,A,B,A,A,B,A,B,B,B,A

## Definindo Participantes de Baixa renda

https://brasilescola.uol.com.br/geografia/renda-per-capita.htm#Renda+per+capita+familiar  

https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/45942-ibge-divulga-rendimento-domiciliar-per-capita-2025-para-brasil-e-unidades-da-federacao  

https://mundoeducacao.uol.com.br/geografia/renda-per-capita.htm  

**https://www.serasa.com.br/blog/baixa-renda/ ()**  

### O que é baixa renda
Baixa renda é um termo utilizado para definir famílias ou indivíduos com renda mensal insuficiente para atender plenamente a necessidades básicas, como alimentação, moradia, saúde, educação e transporte.

Essa classificação varia de acordo com a região e o custo de vida local, mas em geral está associada àqueles que vivem com rendimento abaixo da média nacional.

Pessoas de baixa renda enfrentam diversos desafios que perpetuam o ciclo de pobreza:
 
● falta de acesso a oportunidades de educação e emprego de qualidade;
● preconceito, discriminação e barreiras sociais que dificultam a integração e ascensão social.
● maior exposição a ambientes violentos e a atividades criminosas;
● instabilidade financeira e falta de uma rede de segurança em casos de emergência;
● saúde precária e acesso limitado a cuidados médicos e saneamento básico.
 

**Para saber quem se enquadra nesse critério, basta fazer um cálculo simples: somar a renda da casa e dividi-la pelo número de pessoas que vivem ali. Se o resultado for igual ou inferior a R$706, que representa meio salário mínimo, então aquela família pode ser considerada de baixa renda.**

In [1]:
LIMIAR_BAIXA_RENDA = 706.00

### Definindo a Renda Per Capita Familiar dos Participantes

#### Calculando o ponto médio

In [14]:
faixas_renda = {
    "A": (0, 0),
    "B": (0, 1412),
    "C": (1412.01, 2118),
    "D": (2118.01, 2824),
    "E": (2824.01, 3530),
    "F": (3530.01, 4236),
    "G": (4236.01, 4942),
    "H": (4942.01, 7060),
    "I": (7060.01, 8472),
    "J": (8472.01, 9884),
    "K": (9884.01, 11296),
    "L": (11296.01, 12708),
    "M": (12708.01, 14120),
    "N": (14120.01, 16944),
    "O": (16944.01, 21180),
    "P": (21180.01, 28240),
    "Q": (28240.01, np.inf)
}

In [15]:
renda_media = {}

for faixa, (limite_inferior, limite_superior) in faixas_renda.items():
    if np.isfinite(limite_superior):
        renda_media[faixa] = (limite_inferior + limite_superior) / 2
    else:
        renda_media[faixa] = np.nan

#### Criando a renda familiar estimada

In [17]:
df_santo_amaro["RENDA_FAMILIAR_EST"] = (df_santo_amaro["Q007"].map(renda_media))
df_santo_amaro.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,RENDA_FAMILIAR_EST
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A,1765.005
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A,706.000
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A,0.000
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A,706.000
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A,706.000

#### Calculando a renda per capita

In [19]:
df_santo_amaro["RENDA_PER_CAP_EST"] = np.where(
    df_santo_amaro["Q005"] > 0,
    df_santo_amaro["RENDA_FAMILIAR_EST"] / df_santo_amaro["Q005"],
    np.nan
)
df_santo_amaro

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,RENDA_FAMILIAR_EST,RENDA_PER_CAP_EST
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A,1765.005,441.25125
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A,706.000,176.50000
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A,0.000,0.00000
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A,706.000,176.50000
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A,706.000,176.50000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306106,210066468737,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,E,A,A,3,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A,1765.005,588.33500
4315570,210066478202,2024,2,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,B,F,B,5,A,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,B,A,1765.005,353.00100
4319320,210066481955,2024,3,F,1,1,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,B,B,4,A,B,B,B,D,B,A,B,A,B,B,A,B,A,B,B,D,A,706.000,176.50000
4322809,210066485444,2024,7,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,D,E,C,B,4,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,B,C,E,706.000,176.50000
4330767,210066493402,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,G,B,D,3,A,H,A,D,D,B,B,B,B,B,B,B,D,A,B,D,D,D,6001.005,2000.33500

#### Adicionando a coluna `BAIXA_RENDA`

In [23]:
df_santo_amaro["BAIXA_RENDA"] = np.select(
    [
        df_santo_amaro["RENDA_PER_CAP_EST"].isna(),
        df_santo_amaro["RENDA_PER_CAP_EST"] <= 706
    ],
    [
        None,
        "Sim"
    ],
    default="Nao"
)

df_santo_amaro

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,RENDA_FAMILIAR_EST,RENDA_PER_CAP_EST,BAIXA_RENDA
815,210062065403,2024,2,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,4,A,C,A,B,C,A,A,B,A,A,A,A,B,B,B,A,B,A,1765.005,441.25125,Sim
13148,210062078243,2024,15,M,2,2,1,1,18,NaN,0,2928604,Santo Amaro,29,BA,C,A,A,A,4,B,B,A,B,C,B,A,B,A,A,A,A,A,A,A,A,C,A,706.000,176.50000,Sim
15431,210062080544,2024,3,F,1,2,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,A,D,A,B,6,A,A,A,B,C,A,A,A,A,A,A,A,B,A,B,A,C,A,0.000,0.00000,Sim
16339,210062081464,2024,3,M,1,3,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,D,D,4,A,B,A,B,C,A,A,B,A,A,A,A,B,A,B,B,C,A,706.000,176.50000,Sim
22258,210062087516,2024,8,M,1,2,1,1,2,NaN,0,2928604,Santo Amaro,29,BA,D,D,B,B,4,B,B,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A,706.000,176.50000,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306106,210066468737,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,E,A,A,3,A,C,A,B,C,A,A,B,A,A,A,A,B,A,B,A,C,A,1765.005,588.33500,Sim
4315570,210066478202,2024,2,M,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,B,B,F,B,5,A,C,A,B,C,A,A,B,A,A,A,A,A,A,B,A,B,A,1765.005,353.00100,Sim
4319320,210066481955,2024,3,F,1,1,1,2,0,1.0,0,2928604,Santo Amaro,29,BA,E,E,B,B,4,A,B,B,B,D,B,A,B,A,B,B,A,B,A,B,B,D,A,706.000,176.50000,Sim
4322809,210066485444,2024,7,F,1,3,1,1,5,NaN,0,2928604,Santo Amaro,29,BA,D,E,C,B,4,A,B,A,B,C,A,A,B,A,A,B,A,B,A,B,B,C,E,706.000,176.50000,Sim
4330767,210066493402,2024,1,F,1,3,1,3,0,NaN,1,2928604,Santo Amaro,29,BA,D,G,B,D,3,A,H,A,D,D,B,B,B,B,B,B,B,D,A,B,D,D,D,6001.005,2000.33500,Nao

In [24]:
df_santo_amaro[df_santo_amaro["BAIXA_RENDA"] == None]

Empty DataFrame
Columns: [NU_INSCRICAO, NU_ANO, TP_FAIXA_ETARIA, TP_SEXO, TP_ESTADO_CIVIL, TP_COR_RACA, TP_NACIONALIDADE, TP_ST_CONCLUSAO, TP_ANO_CONCLUIU, TP_ENSINO, IN_TREINEIRO, CO_MUNICIPIO_PROVA, NO_MUNICIPIO_PROVA, CO_UF_PROVA, SG_UF_PROVA, Q001, Q002, Q003, Q004, Q005, Q006, Q007, Q008, Q009, Q010, Q011, Q012, Q013, Q014, Q015, Q016, Q017, Q018, Q019, Q020, Q021, Q022, Q023, RENDA_FAMILIAR_EST, RENDA_PER_CAP_EST, BAIXA_RENDA]
Index: []

In [26]:
df_santo_amaro[
    ["Q005", "Q007", "RENDA_FAMILIAR_EST", "RENDA_PER_CAP_EST", "BAIXA_RENDA"]
].head(20)

       Q005 Q007  RENDA_FAMILIAR_EST  RENDA_PER_CAP_EST BAIXA_RENDA
815       4    C            1765.005         441.251250         Sim
13148     4    B             706.000         176.500000         Sim
15431     6    A               0.000           0.000000         Sim
16339     4    B             706.000         176.500000         Sim
22258     4    B             706.000         176.500000         Sim
27943     1    A               0.000           0.000000         Sim
32317     4    C            1765.005         441.251250         Sim
38485     4    C            1765.005         441.251250         Sim
38782     2    F            3883.005        1941.502500         Nao
40250     4    G            4589.005        1147.251250         Nao
40860     6    B             706.000         117.666667         Sim
43674     2    B             706.000         353.000000         Sim
47425     4    F            3883.005         970.751250         Nao
56297     4    C            1765.005         441.251250         Sim
58625     2    A               0.000           0.000000         Sim
59443     5    B             706.000         141.200000         Sim
60244     2    L           12002.005        6001.002500         Nao
65842     3    F            3883.005        1294.335000         Nao
70055     6    B             706.000         117.666667         Sim
71462     4    B             706.000         176.500000         Sim

In [27]:
df_santo_amaro["BAIXA_RENDA"].value_counts(dropna=False)

BAIXA_RENDA
Sim    1636
Nao     232
NaN       1
Name: count, dtype: int64

In [29]:
df_santo_amaro["Q007"].value_counts(dropna=False).sort_index()

Q007
A    381
B    995
C    249
D     77
E     52
F     38
G     29
H     19
I      9
J      3
K      3
L      5
M      5
N      1
O      1
P      1
Q      1
Name: count, dtype: int64

## Qual foi o desempenho dos estudantes que realizaram o exame na cidade de Santo Amaro?

### Lendo o conjunto de dados de resultados

In [30]:
df_resultados = pd.read_csv(
                './data/2024/RESULTADOS_2024.csv',
                sep=";",
                encoding="latin1"
                )

In [31]:
df_resultados.head()

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,2301406,Aratuba,23,CE,1,1,1,1,1420.0,1383.0,1395.0,1408.0,436.8,377.8,423.4,427.1,CAABADDBBBACACACDEABDBABDDCCBACDCCBAACCABCBAC,BEABBCDABCDBAEEBDDABCCDAADDABACDDAB..........,BCADBCDCEDBDDBDDCDBCBB*BBDEAEEBCDCABBDDAAECEE,CBDCCADBBECCBADEACCBDCACECDDABBDBADBAAEDBCCAB,1,CAEDAACCAEEXCBBAEDBBCAACDEDCBCEECAAEDDDEBBDDB,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,4218004,Tijucas,42,SC,1,1,1,1,1422.0,1384.0,1396.0,1410.0,521.9,601.9,605.5,689.2,EBDEEADAECCAAEDBBEDABACDBCEEDDDEDBDDABDBCCECA,BADBACDAECEDEABBEADDBBDEBEDADEDEEACBBECABCEDA,AACEACADECBCDAEEBEDCBCBEDDCDEAEDEBDABDCECDDDB,DBAEDBECBDDBCCBBABBDECCCCEECBACCDBCDAAABBAAAD,0,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4122404,Rolândia,41,PR,1,1,1,1,1419.0,1385.0,1398.0,1407.0,363.0,548.4,557.2,456.4,CABAECDBADDCDEACABEACEABEDDCEDCDCCBDBDBDDBDCC,DAEDBCDCEBCCECADDACABDEBDCDECEDBEABECBCBBDBCD,BBCABCACDDEECCBCECECADEECCBEADBBEDBDDDEDDEECB,EBADBEDDDBCBCBCDCCECAAADDDECCDBDACACCEAEACDAC,1,BCEAACDEDCAAEDDDEBBDDBECCAEDBBAAACCAEEXCBBCED,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3534401,Osasco,35,SP,1,1,1,1,1421.0,1386.0,1397.0,1409.0,550.7,553.8,605.9,629.1,DDAAECECCBDBECBCBEAAADCBDDBBBEDADBDCCEEBCDAAD,ACCEADCEBDEECEDCCAADBBBCBCEABCD*AECAA........,AACEACBEDBAEEBEABDABCECDBACDCDDDCADEDDDECBEDE,BBBCDACDCABADAEACCECBCDAECECECCECBDEDABEDBCBA,0,DDBDDEBBAAEDECBCEEDCAACDBBCEDBBAEXCCAEAACCAED,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,2111508,São Mateus do Maranhão,21,MA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df_santo_amaro_resultados = df_resultados[
    (df_resultados['NO_MUNICIPIO_PROVA'] == 'Santo Amaro')
    &
    (df_resultados['SG_UF_PROVA'] == 'BA')
].copy()

df_santo_amaro_resultados

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
488,3044462,2024,29170877.0,2928604.0,Santo Amaro,29.0,BA,2.0,1.0,1.0,2928604,Santo Amaro,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3536,638560,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1422.0,1384.0,1396.0,1410.0,440.1,528.6,487.5,588.4,BEBDBDACDBAEBEEEBDAEBBADCCBDAEEADEEDBBBAACDEB,ADDDDCCEECEADCABDAEAEDDACACECEEAEACDCADAECEED,DEDBEDADEDBBDACEBDDAABDABEDDEBAEEAAEBAEEABCAD,CBDDCCECCAABBBBBCDADDCAECCCBDCACCBDEACDEAACCA,1,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,100.0,120.0,100.0,120.0,100.0,540.0
4366,612087,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5623,1457291,2024,29170583.0,2928604.0,Santo Amaro,29.0,BA,2.0,1.0,1.0,2928604,Santo Amaro,29,BA,1,1,1,1,1422.0,1384.0,1396.0,1410.0,369.1,421.5,489.4,550.6,CAECDACEEBACCDABEDEBABDBEADECBAECBBCDABEECADE,CDBAECEBEADAEBDBDDBCDCABEECAAABDDACCEECEDABBD,AAEBAEBDECBBDDECBDDADDDABBCEADBDECAADACBDACAB,ABAEDBCCAEEACDABBDDCBCEDACECCACAEEBCADACDDABC,0,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,100.0,120.0,120.0,120.0,60.0,520.0
11009,1697522,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1421.0,1386.0,1397.0,1409.0,383.4,504.8,443.5,461.6,CBACDDEEDBBDBAEECCDCABBDECDAABCCCCBEABEEEBADD,ABDCACEEBEBACDDAEBCDBEABCCEDDAEBAACEDDBCABECD,CABDEDDECBADEBBADBBDCCEBECDAEAEBDACEABCBCDECE,CDDCDDEEDBABECCEECDDBBADADEBCCAEBABDBAEBDBAED,1,DDBDDEBBAAEDECBCEEDCAACDBBCEDBBAEXCCAEAACCAED,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,120.0,40.0,40.0,100.0,20.0,320.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4318160,1963066,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,0,1,1,0,NaN,1386.0,1397.0,NaN,NaN,551.2,529.1,NaN,NaN,ACACCACECCAAEBDADABCBEBBDCDBBADBAECADDEEDAECB,AADCDDCECADCEBDDBDBBDCEDBCEBDBBDCECEDAEBCBEDA,NaN,1,NaN,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,NaN,1.0,100.0,120.0,120.0,120.0,0.0,460.0
4318351,3044136,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1422.0,1384.0,1396.0,1410.0,460.7,412.5,456.4,434.5,CDCDDEECECDEDBACBDBEEBACAEDCCAEDEBDACCDBBADEA,AEECAADDCCBDDBACDADBACEACDEACECCEDBBEDCCBEDCA,ABABAEDDCCBDDEAEACABDECCBCADDDCCB*ADBEDECEAAC,DDDEBDABCDBEEDADCEBDEECADEDECBDDCDDBBADCCBADC,0,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,80.0,120.0,100.0,80.0,80.0,460.0
4322293,3970923,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1421.0,1386.0,1397.0,1409.0,381.5,383.7,317.6,391.5,ACAEECCDACBCBBAEADEAEEEACDEBBEABEBDEDAAAAAAAB,CEBBABACBABECBBCCDEAABEABCCBBAEAECCECAECDDAEA,AAABAACCBAEBACAEACADBBDBCBAABDAEEBAAAAAABBBEC,AAABEEBEDDBDDCABDEBAACADBDDBBBAADAAABADCECAAA,1,DDBDDEBBAAEDECBCEEDCAACDBBCEDBBAEXCCAEAACCAED,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,100.0,120.0,100.0,80.0,100.0,500.0
4324500,793884,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1422.0,1384.0,1396.0,1410.0,469.6,360.9,472.5,395.1,BCBBADBEEEDEEADBCDAADEADCCAEEECBBBCACADBBACCA,BABAECADEABDDEEACACBCADBCEBBDEEABBAEDDBCDABCE,BCDDCABCECBEDADDADAADDBBBBDEDBBAEAEABACEDDDDA,EDCDDDDDEBDCEDBACCCBBADBCAACDCEECBCBEAECCCECB,1,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,100.0,120.0,120.0,120.0,40.0,500.0
4332383,1870027,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928604,Santo Amaro,29,BA,1,1,1,1,1422.0,1384.0,1396.0,1410.0,522.3,401.2,396.1,446.6,DADEEABEEBDBAEDAABEEBABAAADDEABBDAEAAAAACBCCA,BAEACECDDAAACACABAEAEAAAABADDCEACAABCCAADACDA,ABAADDEBAAEACDADADADADAEAAAAAAAABBAABAEEAAEBA,CECAAEAEABAEAABBACAEBDBAACBCAAEEEAACEAABCAAEA,0,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,80.0,120.0,120.0,80.0,0.0,400.0

In [34]:
areas = {
    'NU_NOTA_CN': 'Ciências da Natureza',
    'NU_NOTA_CH': 'Ciências Humanas',
    'NU_NOTA_LC': 'Linguagens e Códigos',
    'NU_NOTA_MT': 'Matemática',
    'NU_NOTA_REDACAO': 'Redação'
}

estatisticas = df_santo_amaro_resultados[
    list(areas.keys())
].describe().T

estatisticas.index = estatisticas.index.map(areas)

estatisticas

,count,mean,std,min,25%,50%,75%,max
Ciências da Natureza,1263.0,456.011006,62.748021,343.1,404.750,448.30,498.900,662.3
Ciências Humanas,1316.0,465.875456,85.044824,0.0,401.775,462.95,528.650,718.3
Linguagens e Códigos,1316.0,493.025380,67.847246,300.8,449.525,499.70,542.025,707.2
Matemática,1263.0,466.228266,76.797570,0.0,410.950,446.80,501.100,798.5
Redação,1316.0,541.762918,196.917520,0.0,460.000,560.00,660.000,960.0

In [35]:
estatisticas = (
    df_santo_amaro_resultados[list(areas.keys())]
    .describe()
    .T
    .rename(columns={
        'count': 'N',
        'mean': 'Média',
        'std': 'Desvio-padrão',
        'min': 'Mínimo',
        '25%': 'Q1',
        '50%': 'Mediana',
        '75%': 'Q3',
        'max': 'Máximo'
    })
)

estatisticas.index = estatisticas.index.map(areas)

estatisticas

,N,Média,Desvio-padrão,Mínimo,Q1,Mediana,Q3,Máximo
Ciências da Natureza,1263.0,456.011006,62.748021,343.1,404.750,448.30,498.900,662.3
Ciências Humanas,1316.0,465.875456,85.044824,0.0,401.775,462.95,528.650,718.3
Linguagens e Códigos,1316.0,493.025380,67.847246,300.8,449.525,499.70,542.025,707.2
Matemática,1263.0,466.228266,76.797570,0.0,410.950,446.80,501.100,798.5
Redação,1316.0,541.762918,196.917520,0.0,460.000,560.00,660.000,960.0

### Investigando 53 participantes sem nota em CN e MT

In [36]:
df_santo_amaro_resultados[
    list(areas.keys())
].isna().sum()

NU_NOTA_CN         606
NU_NOTA_CH         553
NU_NOTA_LC         553
NU_NOTA_MT         606
NU_NOTA_REDACAO    553
dtype: int64

In [37]:
df_santo_amaro_resultados[
    ['NU_NOTA_CN', 'NU_NOTA_MT']
].isna().value_counts()

NU_NOTA_CN  NU_NOTA_MT
False       False         1263
True        True           606
Name: count, dtype: int64

In [38]:
(df_santo_amaro_resultados[list(areas.keys())] == 0).sum()

NU_NOTA_CN          0
NU_NOTA_CH          1
NU_NOTA_LC          0
NU_NOTA_MT          1
NU_NOTA_REDACAO    80
dtype: int64

In [39]:
df_santo_amaro_resultados[
    ['NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_REDACAO']
].isna().value_counts()

NU_NOTA_CH  NU_NOTA_LC  NU_NOTA_REDACAO
False       False       False              1316
True        True        True                553
Name: count, dtype: int64

Em 2024, foram identificados 1.316 registros de participantes que realizaram o ENEM em Santo Amaro. Desses, 1.263 apresentam notas disponíveis para Ciências da Natureza e Matemática, enquanto 1.316 apresentam notas disponíveis para Ciências Humanas, Linguagens e Códigos e Redação. A diferença decorre de 53 registros sem notas de Ciências da Natureza e Matemática.